#!/bin/ksh -p
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)setup.ksh	1.1	09/06/22 SMI"
#

. $STF_SUITE/commands.cfg
. $STF_SUITE/include/default_common_varible.kshlib
. $STF_SUITE/include/libtest.kshlib
. $STF_SUITE/tests/functional/userquota/userquota_common.kshlib

#verify_runnable "both"

#if ! is_userquota_supported; then
#	log_unsupported "userquota is not supported in this system."
#fi

#log_must clean_user_group
if [ $(id -u) != 0 ]; then
         echo "You Must run as root"
	 exit 1	
fi

if [ $# != 1 ]
then
echo "USAGE: ./setup disk"
exit 1;
fi

log_must add_group $QGROUP
echo " add_group done "
log_must add_user $QGROUP $QUSER1
echo " add_user 1 done "
log_must add_user $QGROUP $QUSER2
echo " add_user 2 done "

#DISK=${DISKS%% *}
DISK=$1
default_setup $DISK
