#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.6	08/08/15 SMI"
#

STF_ROOT_CONFIGURE=
STF_USER_CONFIGURE=

STF_ROOT_SETUP=setup
STF_USER_SETUP=

STF_ROOT_CLEANUP=cleanup
STF_USER_CLEANUP=

STF_ROOT_TESTCASES=snapshot_001_pos snapshot_002_pos \
    snapshot_003_pos snapshot_004_pos \
    snapshot_005_pos snapshot_006_pos \
    snapshot_007_pos snapshot_008_pos \
    snapshot_009_pos snapshot_010_pos \
    snapshot_011_pos snapshot_012_pos \
    snapshot_013_pos snapshot_014_pos \
    snapshot_015_pos snapshot_016_pos \
    snapshot_017_pos \
    rollback_001_pos rollback_002_pos \
    rollback_003_pos \
    clone_001_pos
STF_USER_TESTCASES=

STF_ENVFILES=snapshot.cfg

STF_DONTBUILDMODES=true
 
include $(STF_TOOLS)/Makefiles/Makefile.master
