#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.7	09/06/22 SMI"
#

STF_ROOT_CONFIGURE=
STF_USER_CONFIGURE=

STF_ROOT_SETUP=
STF_USER_SETUP=

STF_ROOT_CLEANUP=
STF_USER_CLEANUP=

STF_ROOT_TESTCASES=
STF_USER_TESTCASES=

STF_ENVFILES=
STF_INCLUDES=

STF_DATAFILES = \
zfs-broken-mirror1.dat.Z  zfs-pool-v2raidz3.dat.Z \
zfs-broken-mirror2.dat.Z  zfs-pool-v2stripe1.dat.Z \
zfs-pool-v1.dat.Z         zfs-pool-v2stripe2.dat.Z \
zfs-pool-v1mirror1.dat.Z  zfs-pool-v2stripe3.dat.Z \
zfs-pool-v1mirror2.dat.Z  zfs-pool-v3.dat.Z \
zfs-pool-v1mirror3.dat.Z  zfs-pool-v3mirror1.dat.Z \
zfs-pool-v1raidz1.dat.Z   zfs-pool-v3mirror2.dat.Z \
zfs-pool-v1raidz2.dat.Z   zfs-pool-v3mirror3.dat.Z \
zfs-pool-v1raidz3.dat.Z   zfs-pool-v3raidz1.dat.Z \
zfs-pool-v1stripe1.dat.Z  zfs-pool-v3raidz21.dat.Z \
zfs-pool-v1stripe2.dat.Z  zfs-pool-v3raidz22.dat.Z \
zfs-pool-v1stripe3.dat.Z  zfs-pool-v3raidz23.dat.Z \
zfs-pool-v2.dat.Z         zfs-pool-v3raidz2.dat.Z \
zfs-pool-v2mirror1.dat.Z  zfs-pool-v3raidz3.dat.Z \
zfs-pool-v2mirror2.dat.Z  zfs-pool-v3stripe1.dat.Z \
zfs-pool-v2mirror3.dat.Z  zfs-pool-v3stripe2.dat.Z \
zfs-pool-v2raidz1.dat.Z   zfs-pool-v3stripe3.dat.Z \
zfs-pool-v2raidz2.dat.Z   zfs-pool-vBROKEN.dat.Z \
zfs-pool-v3hotspare1.dat.Z zfs-pool-v3hotspare2.dat.Z \
zfs-pool-v3hotspare3.dat.Z zfs-pool-v4.dat.Z \
zfs-pool-v5.dat.Z 	  zfs-pool-v6.dat.Z \
zfs-pool-v7.dat.Z	  zfs-pool-v8.dat.Z \
zfs-pool-v9.dat.Z	  zfs-pool-v10.dat.Z \
zfs-pool-v11.dat.Z	  zfs-pool-v12.dat.Z \
zfs-pool-v13.dat.Z	  zfs-pool-v14.dat.Z \
zfs-pool-v15.dat.Z	zfs-pool-v999.dat.Z

STF_DONTBUILDMODES=true

include ${STF_TOOLS}/Makefiles/Makefile.master
